export const books = [
    {
        "id": 1,
        "title_bn": "পথের পাঁচালি",
        "title_en": "Pather Panchali",
        "author_bn": "বিভূতিভূষণ বন্দ্যোপাধ্যায়",
        "author_en": "Bibhutibhushan Bandyopadhyay",
        "category": "Novel",
        "tags": ["classic", "coming-of-age", "rural life", "best seller"],
        "price": 350,
        "discount_price": 300,
        "language": "Bangla",
        "cover_image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRnryA-bWQlSamfU-Smu86VYO9hgmWqITs_pQ&s",
        "description": "এই উপন্যাসে অপু ও তার পরিবারের জীবনযাত্রা, দারিদ্র্য, স্বপ্ন ও সংগ্রামের এক অনুপম চিত্র তুলে ধরা হয়েছে।",
        "publication": "Ananda Publishers"
    },
    {
        "id": 2,
        "title_bn": "চোখের বালি",
        "title_en": "Chokher Bali",
        "author_bn": "রবীন্দ্রনাথ ঠাকুর",
        "author_en": "Rabindranath Tagore",
        "category": "Drama",
        "tags": ["classic", "romance", "psychological", "best seller"],
        "price": 320,
        "discount_price": 280,
        "language": "Bangla",
        "cover_image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRnryA-bWQlSamfU-Smu86VYO9hgmWqITs_pQ&s",
        "description": "একজন বিধবার জটিল মনস্তত্ত্ব, প্রেম ও প্রতিশোধের কাহিনি। রবীন্দ্র সাহিত্যের অন্যতম সেরা সৃষ্টি।",
        "publication": "Visva-Bharati"
    },
    {
        "id": 3,
        "title_bn": "শংকর",
        "title_en": "Shankar",
        "author_bn": "মানিক বন্দ্যোপাধ্যায়",
        "author_en": "Manik Bandopadhyay",
        "category": "Novel",
        "tags": ["realism", "social issues"],
        "price": 300,
        "discount_price": 260,
        "language": "Bangla",
        "cover_image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRnryA-bWQlSamfU-Smu86VYO9hgmWqITs_pQ&s",
        "description": "মানবজীবনের কঠিন বাস্তবতা এবং সমাজের নানা বৈষম্যের প্রতিবিম্ব এই উপন্যাসে ফুটে উঠেছে।",
        "publication": "Dey's Publishing"
    },
    {
        "id": 4,
        "title_bn": "দেবদাস",
        "title_en": "Devdas",
        "author_bn": "শরৎচন্দ্র চট্টোপাধ্যায়",
        "author_en": "Sarat Chandra Chattopadhyay",
        "category": "Romance",
        "tags": ["tragedy", "classic", "best seller"],
        "price": 340,
        "discount_price": 300,
        "language": "Bangla",
        "cover_image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRnryA-bWQlSamfU-Smu86VYO9hgmWqITs_pQ&s",
        "description": "প্রেম, সমাজের চাপ এবং মানসিক টানাপোড়েনের এক হৃদয়বিদারক উপাখ্যান।",
        "publication": "Ananda Publishers"
    },
    {
        "id": 5,
        "title_bn": "আরন্যক",
        "title_en": "Aranyak",
        "author_bn": "বিভূতিভূষণ বন্দ্যোপাধ্যায়",
        "author_en": "Bibhutibhushan Bandyopadhyay",
        "category": "Nature",
        "tags": ["wilderness", "philosophy", "best seller"],
        "price": 360,
        "discount_price": 310,
        "language": "Bangla",
        "cover_image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRnryA-bWQlSamfU-Smu86VYO9hgmWqITs_pQ&s",
        "description": "বন-জঙ্গল এবং প্রকৃতির মাঝে মানুষের অস্তিত্বের খোঁজের এক আত্মদর্শী গল্প।",
        "publication": "Mitralaya"
    },
    {
        "id": 6,
        "title_bn": "পরিণীতা",
        "title_en": "Parineeta",
        "author_bn": "শরৎচন্দ্র চট্টোপাধ্যায়",
        "author_en": "Sarat Chandra Chattopadhyay",
        "category": "Romance",
        "tags": ["classic", "drama", "best seller"],
        "price": 330,
        "discount_price": 290,
        "language": "Bangla",
        "cover_image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRnryA-bWQlSamfU-Smu86VYO9hgmWqITs_pQ&s",
        "description": "শরৎচন্দ্রের রোমান্টিক ঘরানার উপন্যাস, যেখানে সম্পর্কের সূক্ষ্মতা ও সামাজিক বাধা ফুটে উঠেছে।",
        "publication": "New Age Publishers"
    },
    {
        "id": 7,
        "title_bn": "গৃহদাহ",
        "title_en": "Grihadaha",
        "author_bn": "রবীন্দ্রনাথ ঠাকুর",
        "author_en": "Rabindranath Tagore",
        "category": "Drama",
        "tags": ["psychological", "philosophy"],
        "price": 300,
        "discount_price": 270,
        "language": "Bangla",
        "cover_image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRnryA-bWQlSamfU-Smu86VYO9hgmWqITs_pQ&s",
        "description": "মানব মন ও সমাজের নিয়মের মধ্যে দ্বন্দ্ব নিয়ে একটি গভীর দার্শনিক উপন্যাস।",
        "publication": "Visva-Bharati"
    },
    {
        "id": 8,
        "title_bn": "সতীনাথ",
        "title_en": "Satinath",
        "author_bn": "তারাশঙ্কর বন্দ্যোপাধ্যায়",
        "author_en": "Tarashankar Bandopadhyay",
        "category": "Social",
        "tags": ["realism", "village life"],
        "price": 370,
        "discount_price": 330,
        "language": "Bangla",
        "cover_image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRnryA-bWQlSamfU-Smu86VYO9hgmWqITs_pQ&s",
        "description": "বাংলার গ্রামীণ সমাজব্যবস্থা ও চরিত্রদের বাস্তব চিত্র তুলে ধরা হয়েছে।",
        "publication": "Ananda Publishers"
    },
    {
        "id": 9,
        "title_bn": "অপরিচিতা",
        "title_en": "Aparichita",
        "author_bn": "রবীন্দ্রনাথ ঠাকুর",
        "author_en": "Rabindranath Tagore",
        "category": "Short Story",
        "tags": ["romance", "social", "classic"],
        "price": 250,
        "discount_price": 220,
        "language": "Bangla",
        "cover_image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRnryA-bWQlSamfU-Smu86VYO9hgmWqITs_pQ&s",
        "description": "নারী-পুরুষ সম্পর্ক এবং আত্মমর্যাদার টানাপোড়েন নিয়ে এক ছোটগল্প।",
        "publication": "Visva-Bharati"
    },
    {
        "id": 10,
        "title_bn": "পুতুলনাচের ইতিকথা",
        "title_en": "Putul Nacher Itikotha",
        "author_bn": "মানিক বন্দ্যোপাধ্যায়",
        "author_en": "Manik Bandopadhyay",
        "category": "Philosophical",
        "tags": ["existential", "psychological", "best seller"],
        "price": 400,
        "discount_price": 360,
        "language": "Bangla",
        "cover_image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRnryA-bWQlSamfU-Smu86VYO9hgmWqITs_pQ&s",
        "description": "মানব জীবনের অর্থহীনতা ও উদ্দেশ্য নিয়ে এক গভীর দর্শনের উপাখ্যান।",
        "publication": "Dey's Publishing"
    },

    {
        "id": 11,
        "title_bn": "হংসবলাকা",
        "title_en": "Hansbalaka",
        "author_bn": "সুনীল গঙ্গোপাধ্যায়",
        "author_en": "Sunil Gangopadhyay",
        "category": "Poetry",
        "tags": ["modern poetry", "best seller"],
        "price": 280,
        "discount_price": 250,
        "language": "Bangla",
        "cover_image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRnryA-bWQlSamfU-Smu86VYO9hgmWqITs_pQ&s",
        "description": "আধুনিক প্রেম, বেদনা ও জীবনের নানা রঙ নিয়ে গঠিত কাব্যগ্রন্থ।",
        "publication": "Ananda Publishers"
    },
    {
        "id": 12,
        "title_bn": "ছিন্নপত্রাবলী",
        "title_en": "Chinnapatrabali",
        "author_bn": "রবীন্দ্রনাথ ঠাকুর",
        "author_en": "Rabindranath Tagore",
        "category": "Letters",
        "tags": ["personal", "thoughts"],
        "price": 290,
        "discount_price": 250,
        "language": "Bangla",
        "cover_image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRnryA-bWQlSamfU-Smu86VYO9hgmWqITs_pQ&s",
        "description": "রবীন্দ্রনাথের জীবনের নানা দিক উঠে এসেছে তার চিঠিপত্রে।",
        "publication": "Visva-Bharati"
    },
    {
        "id": 13,
        "title_bn": "কবুলিওয়ালা",
        "title_en": "Kabuliwala",
        "author_bn": "রবীন্দ্রনাথ ঠাকুর",
        "author_en": "Rabindranath Tagore",
        "category": "Short Story",
        "tags": ["emotion", "parenthood", "best seller"],
        "price": 240,
        "discount_price": 210,
        "language": "Bangla",
        "cover_image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRnryA-bWQlSamfU-Smu86VYO9hgmWqITs_pQ&s",
        "description": "এক আফগান ব্যবসায়ী ও এক ছোট বালিকার হৃদয়স্পর্শী সম্পর্কের গল্প।",
        "publication": "Visva-Bharati"
    },
    {
        "id": 14,
        "title_bn": "অরণ্যের দিনরাত্রি",
        "title_en": "Aranyer Din Ratri",
        "author_bn": "সত্যজিৎ রায়",
        "author_en": "Satyajit Ray",
        "category": "Travel",
        "tags": ["youth", "friendship", "philosophy"],
        "price": 350,
        "discount_price": 310,
        "language": "Bangla",
        "cover_image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRnryA-bWQlSamfU-Smu86VYO9hgmWqITs_pQ&s",
        "description": "চার বন্ধুর জঙ্গলে বেড়াতে গিয়ে জীবনের নানা উপলব্ধির গল্প।",
        "publication": "Ananda Publishers"
    },
    {
        "id": 15,
        "title_bn": "গণদেবতা",
        "title_en": "Ganadevata",
        "author_bn": "তারাশঙ্কর বন্দ্যোপাধ্যায়",
        "author_en": "Tarashankar Bandopadhyay",
        "category": "Social",
        "tags": ["politics", "rural", "best seller"],
        "price": 420,
        "discount_price": 380,
        "language": "Bangla",
        "cover_image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRnryA-bWQlSamfU-Smu86VYO9hgmWqITs_pQ&s",
        "description": "গ্রামবাংলার রাজনীতি ও জনগণের মনের কথা তুলে ধরা হয়েছে।",
        "publication": "Mitralaya"
    },
    {
        "id": 16,
        "title_bn": "আত্মজীবনী",
        "title_en": "Atmojiboni",
        "author_bn": "লালন ফকির",
        "author_en": "Lalon Fakir",
        "category": "Biography",
        "tags": ["spiritual", "folk"],
        "price": 280,
        "discount_price": 240,
        "language": "Bangla",
        "cover_image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRnryA-bWQlSamfU-Smu86VYO9hgmWqITs_pQ&s",
        "description": "লালনের চিন্তা, দর্শন ও জীবনসংগ্রামের এক আত্মকথা।",
        "publication": "Bangla Academy"
    },
    {
        "id": 17,
        "title_bn": "দত্তা",
        "title_en": "Datta",
        "author_bn": "শরৎচন্দ্র চট্টোপাধ্যায়",
        "author_en": "Sarat Chandra Chattopadhyay",
        "category": "Romance",
        "tags": ["classic", "relationship"],
        "price": 340,
        "discount_price": 300,
        "language": "Bangla",
        "cover_image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRnryA-bWQlSamfU-Smu86VYO9hgmWqITs_pQ&s",
        "description": "নারী স্বাধীনতা ও প্রেমের গল্পের এক মাইলফলক রচনা।",
        "publication": "New Age Publishers"
    },
    {
        "id": 18,
        "title_bn": "মেঘে ঢাকা তারা",
        "title_en": "Meghe Dhaka Tara",
        "author_bn": "রিতিক ঘটক",
        "author_en": "Ritwik Ghatak",
        "category": "Drama",
        "tags": ["partition", "family", "tragedy"],
        "price": 390,
        "discount_price": 350,
        "language": "Bangla",
        "cover_image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRnryA-bWQlSamfU-Smu86VYO9hgmWqITs_pQ&s",
        "description": "দেশভাগ পরবর্তী দুঃখ-ব্যথা এবং জীবনের অসহায়তা নিয়ে এক মর্মস্পর্শী কাহিনি।",
        "publication": "Dey's Publishing"
    },
    {
        "id": 19,
        "title_bn": "ফেলুদা সমগ্র",
        "title_en": "Feluda Samagra",
        "author_bn": "সত্যজিৎ রায়",
        "author_en": "Satyajit Ray",
        "category": "Detective",
        "tags": ["adventure", "mystery", "best seller"],
        "price": 600,
        "discount_price": 550,
        "language": "Bangla",
        "cover_image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRnryA-bWQlSamfU-Smu86VYO9hgmWqITs_pQ&s",
        "description": "ভারতের বিখ্যাত গোয়েন্দা ফেলুদার রোমাঞ্চকর কাহিনির সংগ্রহ।",
        "publication": "Ananda Publishers"
    },
    {
        "id": 20,
        "title_bn": "শব্দের খোঁজে",
        "title_en": "Shobder Khoje",
        "author_bn": "শক্তি চট্টোপাধ্যায়",
        "author_en": "Shakti Chattopadhyay",
        "category": "Poetry",
        "tags": ["modern poetry", "philosophy"],
        "price": 270,
        "discount_price": 230,
        "language": "Bangla",
        "cover_image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRnryA-bWQlSamfU-Smu86VYO9hgmWqITs_pQ&s",
        "description": "আধুনিক বাংলা কবিতার এক দিকপাল রচনার সংকলন।",
        "publication": "Mitralaya"
    },
    {
        "id": 21,
        "title_bn": "কবিতার খোঁজে",
        "title_en": "Kobitar Khoje",
        "author_bn": "জীবনানন্দ দাশ",
        "author_en": "Jibanananda Das",
        "category": "Poetry",
        "tags": ["modern poetry", "bestseller"],
        "price": 300,
        "discount_price": 260,
        "language": "Bangla",
        "cover_image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRnryA-bWQlSamfU-Smu86VYO9hgmWqITs_pQ&s",
        "description": "জীবন ও প্রকৃতির অনুপম বর্ণনায় সমৃদ্ধ একটি কবিতার সংকলন।",
        "publication": "Ananda Publishers"
    },
    {
        "id": 22,
        "title_bn": "স্মৃতির শহর",
        "title_en": "Smritir Shohor",
        "author_bn": "হুমায়ুন আজাদ",
        "author_en": "Humayun Azad",
        "category": "Fiction",
        "tags": ["contemporary", "philosophical"],
        "price": 320,
        "discount_price": 280,
        "language": "Bangla",
        "cover_image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRnryA-bWQlSamfU-Smu86VYO9hgmWqITs_pQ&s",
        "description": "মানুষ ও শহরের সম্পর্ক নিয়ে একটি দার্শনিক উপন্যাস।",
        "publication": "Agamee Prakashani"
    },
    {
        "id": 23,
        "title_bn": "রাত্রি ও দিন",
        "title_en": "Ratri O Din",
        "author_bn": "শীর্ষেন্দু মুখোপাধ্যায়",
        "author_en": "Shirshendu Mukhopadhyay",
        "category": "Novel",
        "tags": ["psychological", "bestseller"],
        "price": 280,
        "discount_price": 240,
        "language": "Bangla",
        "cover_image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRnryA-bWQlSamfU-Smu86VYO9hgmWqITs_pQ&s",
        "description": "চরিত্রের অন্তর্জগত ও দ্বন্দ্বের গল্প।",
        "publication": "Dey's Publishing"
    },
    {
        "id": 24,
        "title_bn": "ছায়ার দিনগুলি",
        "title_en": "Chayar Dinguli",
        "author_bn": "বুদ্ধদেব বসু",
        "author_en": "Buddhadeb Basu",
        "category": "Memoir",
        "tags": ["literature", "autobiography"],
        "price": 350,
        "discount_price": 300,
        "language": "Bangla",
        "cover_image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRnryA-bWQlSamfU-Smu86VYO9hgmWqITs_pQ&s",
        "description": "একজন কবির জীবনের স্মৃতিচারণ।",
        "publication": "Signet Press"
    },
    {
        "id": 25,
        "title_bn": "প্রেমের পদাবলী",
        "title_en": "Premer Padaboli",
        "author_bn": "রবীন্দ্রনাথ ঠাকুর",
        "author_en": "Rabindranath Tagore",
        "category": "Poetry",
        "tags": ["romantic", "classic"],
        "price": 260,
        "discount_price": 220,
        "language": "Bangla",
        "cover_image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRnryA-bWQlSamfU-Smu86VYO9hgmWqITs_pQ&s",
        "description": "রোমান্টিক কবিতার এক অসাধারণ সংগ্রহ।",
        "publication": "Visva-Bharati"
    },
    {
        "id": 26,
        "title_bn": "আলো ও আঁধার",
        "title_en": "Alo O Andhar",
        "author_bn": "সুনীল গঙ্গোপাধ্যায়",
        "author_en": "Sunil Gangopadhyay",
        "category": "Novel",
        "tags": ["bestseller", "drama"],
        "price": 290,
        "discount_price": 250,
        "language": "Bangla",
        "cover_image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRnryA-bWQlSamfU-Smu86VYO9hgmWqITs_pQ&s",
        "description": "জীবনের আলো ও আঁধারের গল্প।",
        "publication": "Mitralaya"
    },
    {
        "id": 27,
        "title_bn": "তিমির পেছনে আলো",
        "title_en": "Timir Peshone Alo",
        "author_bn": "তসলিমা নাসরিন",
        "author_en": "Taslima Nasrin",
        "category": "Essay",
        "tags": ["feminism", "controversial"],
        "price": 300,
        "discount_price": 260,
        "language": "Bangla",
        "cover_image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRnryA-bWQlSamfU-Smu86VYO9hgmWqITs_pQ&s",
        "description": "নারীর অধিকার ও সমাজ নিয়ে সরাসরি ভাষ্যে একটি প্রবন্ধ সংকলন।",
        "publication": "Chandrabindu"
    },
    {
        "id": 28,
        "title_bn": "একুশে ফেব্রুয়ারি",
        "title_en": "Ekushey February",
        "author_bn": "আনিসুজ্জামান",
        "author_en": "Anisuzzaman",
        "category": "History",
        "tags": ["language movement", "non-fiction"],
        "price": 280,
        "discount_price": 240,
        "language": "Bangla",
        "cover_image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRnryA-bWQlSamfU-Smu86VYO9hgmWqITs_pQ&s",
        "description": "ভাষা আন্দোলনের ইতিহাস ও তাৎপর্য।",
        "publication": "Bangla Academy"
    },
    {
        "id": 29,
        "title_bn": "ছায়ার কবিতা",
        "title_en": "Chayar Kobita",
        "author_bn": "শক্তি চট্টোপাধ্যায়",
        "author_en": "Shakti Chattopadhyay",
        "category": "Poetry",
        "tags": ["modern poetry"],
        "price": 270,
        "discount_price": 230,
        "language": "Bangla",
        "cover_image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRnryA-bWQlSamfU-Smu86VYO9hgmWqITs_pQ&s",
        "description": "আধুনিক কবিতার এক রূপান্তরময় ধারার সৃষ্টি।",
        "publication": "Mitralaya"
    },
    {
        "id": 30,
        "title_bn": "অন্ধকার সময়",
        "title_en": "Andhokar Somoy",
        "author_bn": "হাসান আজিজুল হক",
        "author_en": "Hasan Azizul Haque",
        "category": "Short Stories",
        "tags": ["realism", "war"],
        "price": 320,
        "discount_price": 280,
        "language": "Bangla",
        "cover_image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRnryA-bWQlSamfU-Smu86VYO9hgmWqITs_pQ&s",
        "description": "বাংলাদেশের ইতিহাস ও যুদ্ধকালীন জীবনের প্রতিচ্ছবি।",
        "publication": "Abosar Prokashoni"
    },
    {
        "id": 31,
        "title_bn": "ছায়া মানব",
        "title_en": "Chhaya Manob",
        "author_bn": "জাফর ইকবাল",
        "author_en": "Zafar Iqbal",
        "category": "Science Fiction",
        "tags": ["sci-fi", "bestseller"],
        "price": 360,
        "discount_price": 310,
        "language": "Bangla",
        "cover_image": "https://www.boipokabd.com/storage/app/public/product/thumbnail/2024-01-04-659655865d3e0.png",
        "description": "বিজ্ঞান আর কল্পনার মিশেলে তৈরি এক নতুন জগতের গল্প।",
        "publication": "Tamralipi"
    },
    {
        "id": 32,
        "title_bn": "নিঃসঙ্গ নক্ষত্র",
        "title_en": "Nissongo Nokkhotro",
        "author_bn": "হুমায়ূন আহমেদ",
        "author_en": "Humayun Ahmed",
        "category": "Novel",
        "tags": ["drama", "emotional"],
        "price": 340,
        "discount_price": 300,
        "language": "Bangla",
        "cover_image": "https://www.boipokabd.com/storage/app/public/product/thumbnail/2024-01-04-659655865d3e0.png",
        "description": "এক নিঃসঙ্গ মানুষ ও তার অতীতের গল্প।",
        "publication": "Annesha"
    },
    {
        "id": 33,
        "title_bn": "সময়ের ছায়া",
        "title_en": "Shomoyer Chhaya",
        "author_bn": "মুহম্মদ জাফর ইকবাল",
        "author_en": "Muhammed Zafar Iqbal",
        "category": "Science Fiction",
        "tags": ["time travel", "bestseller"],
        "price": 400,
        "discount_price": 360,
        "language": "Bangla",
        "cover_image": "https://www.boipokabd.com/storage/app/public/product/thumbnail/2024-01-04-659655865d3e0.png",
        "description": "ভবিষ্যতের পথে সময়ের ভেতর যাত্রা।",
        "publication": "Sheba Prokashoni"
    },
    {
        "id": 34,
        "title_bn": "হারানো দিনগুলি",
        "title_en": "Harano Dinguli",
        "author_bn": "সুনীল গঙ্গোপাধ্যায়",
        "author_en": "Sunil Gangopadhyay",
        "category": "Novel",
        "tags": ["nostalgic", "drama"],
        "price": 330,
        "discount_price": 280,
        "language": "Bangla",
        "cover_image": "https://www.boipokabd.com/storage/app/public/product/thumbnail/2024-01-04-659655865d3e0.png",
        "description": "একজন মানুষের জীবনের স্মৃতি ও বেদনার কাহিনী।",
        "publication": "Dey’s Publishing"
    },
    {
        "id": 35,
        "title_bn": "জীবনের মানে",
        "title_en": "Jiboner Mane",
        "author_bn": "হাসান আজিজুল হক",
        "author_en": "Hasan Azizul Haque",
        "category": "Philosophy",
        "tags": ["thought-provoking", "classic"],
        "price": 300,
        "discount_price": 260,
        "language": "Bangla",
        "cover_image": "https://www.boipokabd.com/storage/app/public/product/thumbnail/2024-01-04-659655865d3e0.png",
        "description": "জীবন, সমাজ ও মানুষের গভীর ভাবনার রূপায়ন।",
        "publication": "Mowla Brothers"
    },
    {
        "id": 36,
        "title_bn": "রোবটের প্রেম",
        "title_en": "Roboter Prem",
        "author_bn": "মুহম্মদ জাফর ইকবাল",
        "author_en": "Muhammed Zafar Iqbal",
        "category": "Science Fiction",
        "tags": ["robot", "romantic"],
        "price": 380,
        "discount_price": 340,
        "language": "Bangla",
        "cover_image": "https://www.boipokabd.com/storage/app/public/product/thumbnail/2024-01-04-659655865d3e0.png",
        "description": "রোবট ও মানুষের সম্পর্ক নিয়ে আবেগঘন গল্প।",
        "publication": "Tamralipi"
    },
    {
        "id": 37,
        "title_bn": "আঁধারের পরে আলো",
        "title_en": "Andharer Pore Alo",
        "author_bn": "হুমায়ূন আহমেদ",
        "author_en": "Humayun Ahmed",
        "category": "Novel",
        "tags": ["hope", "bestseller"],
        "price": 360,
        "discount_price": 310,
        "language": "Bangla",
        "cover_image": "https://www.boipokabd.com/storage/app/public/product/thumbnail/2024-01-04-659655865d3e0.png",
        "description": "আঁধারের পরেও জীবন আলোয় ভরে উঠতে পারে।",
        "publication": "Ananya"
    },
    {
        "id": 38,
        "title_bn": "তৃতীয় চোখ",
        "title_en": "Tritiyo Chokh",
        "author_bn": "রবীন্দ্রনাথ ঠাকুর",
        "author_en": "Rabindranath Tagore",
        "category": "Philosophy",
        "tags": ["spiritual", "bestseller"],
        "price": 310,
        "discount_price": 270,
        "language": "Bangla",
        "cover_image": "https://www.boipokabd.com/storage/app/public/product/thumbnail/2024-01-04-659655865d3e0.png",
        "description": "আত্মজ্ঞান ও দর্শনের এক অনন্য সৃষ্টি।",
        "publication": "Visva Bharati"
    },
    {
        "id": 39,
        "title_bn": "শেষ দিন",
        "title_en": "Shesh Din",
        "author_bn": "আনিসুল হক",
        "author_en": "Anisul Hoque",
        "category": "Drama",
        "tags": ["drama", "heart-touching"],
        "price": 280,
        "discount_price": 240,
        "language": "Bangla",
        "cover_image": "https://www.boipokabd.com/storage/app/public/product/thumbnail/2024-01-04-659655865d3e0.png",
        "description": "একজন মৃত্যুপথযাত্রীর শেষ দিনের কাহিনী।",
        "publication": "Prothoma"
    },
    {
        "id": 40,
        "title_bn": "অদৃশ্য শহর",
        "title_en": "Odriśśho Shohor",
        "author_bn": "রেজাউর রহমান",
        "author_en": "Rezaur Rahman",
        "category": "Science Fiction",
        "tags": ["urban sci-fi", "thriller"],
        "price": 370,
        "discount_price": 330,
        "language": "Bangla",
        "cover_image": "https://www.boipokabd.com/storage/app/public/product/thumbnail/2024-01-04-659655865d3e0.png",
        "description": "যে শহর নেই কোথাও, কিন্তু আছে সকলের মনে।",
        "publication": "Mawla Brothers"
    },
    {
        "id": 41,
        "title_bn": "ছায়ার মানুষ",
        "title_en": "Chhaya'r Manush",
        "author_bn": "সেলিনা হোসেন",
        "author_en": "Selina Hossain",
        "category": "Drama",
        "tags": ["drama", "social issues"],
        "price": 300,
        "discount_price": 260,
        "language": "Bangla",
        "cover_image": "https://www.boipokabd.com/storage/app/public/product/thumbnail/2024-01-04-659655865d3e0.png",
        "description": "এই নাটকে তুলে ধরা হয়েছে সমাজের ছায়াময় দিকগুলোর গল্প।",
        "publication": "Ananya"
    },
    {
        "id": 42,
        "title_bn": "স্বপ্নের পাখি",
        "title_en": "Shopner Pakhi",
        "author_bn": "হুমায়ূন আহমেদ",
        "author_en": "Humayun Ahmed",
        "category": "Fiction",
        "tags": ["fiction", "bestseller"],
        "price": 350,
        "discount_price": 310,
        "language": "Bangla",
        "cover_image": "https://www.boipokabd.com/storage/app/public/product/thumbnail/2024-01-04-659655865d3e0.png",
        "description": "এক যুবকের জীবনের স্বপ্ন ও বাস্তবতার দ্বন্দ্বের কাহিনী।",
        "publication": "Anyaprokash"
    },
    {
        "id": 43,
        "title_bn": "শেষ চিঠি",
        "title_en": "Shesh Chithi",
        "author_bn": "সানজিদা রহমান",
        "author_en": "Sanjida Rahman",
        "category": "Short Story",
        "tags": ["short story", "emotional"],
        "price": 260,
        "discount_price": 220,
        "language": "Bangla",
        "cover_image": "https://www.boipokabd.com/storage/app/public/product/thumbnail/2024-01-04-659655865d3e0.png",
        "description": "কিছু অসমাপ্ত ভালোবাসার চিঠির গল্প।",
        "publication": "Adorn Publication"
    },
    {
        "id": 44,
        "title_bn": "তপ্ত মরু",
        "title_en": "Toptu Moru",
        "author_bn": "আব্দুল্লাহ আবু সায়ীদ",
        "author_en": "Abdullah Abu Sayeed",
        "category": "Drama",
        "tags": ["drama", "social"],
        "price": 320,
        "discount_price": 280,
        "language": "Bangla",
        "cover_image": "https://www.boipokabd.com/storage/app/public/product/thumbnail/2024-01-04-659655865d3e0.png",
        "description": "মরুভূমির মাঝে বেঁচে থাকার লড়াইয়ের গল্প।",
        "publication": "Bengal Publications"
    },
    {
        "id": 45,
        "title_bn": "আলোর কণা",
        "title_en": "Alor Kona",
        "author_bn": "তাসনিম জারা",
        "author_en": "Tasnim Zarah",
        "category": "Short Story",
        "tags": ["short story", "hope"],
        "price": 240,
        "discount_price": 200,
        "language": "Bangla",
        "cover_image": "https://www.boipokabd.com/storage/app/public/product/thumbnail/2024-01-04-659655865d3e0.png",
        "description": "ছোট ছোট গল্পে জীবনের উজ্জ্বল মুহূর্তের প্রতিফলন।",
        "publication": "Prothoma"
    },
    {
        "id": 46,
        "title_bn": "অন্তরালের গল্প",
        "title_en": "Ontoraler Golpo",
        "author_bn": "সুমন রেজা",
        "author_en": "Sumon Reza",
        "category": "Fiction",
        "tags": ["fiction", "mystery"],
        "price": 280,
        "discount_price": 240,
        "language": "Bangla",
        "cover_image": "https://www.boipokabd.com/storage/app/public/product/thumbnail/2024-01-04-659655865d3e0.png",
        "description": "অন্তরালের রহস্যময় এক গল্প যা পাঠককে ভাবাবে।",
        "publication": "Puthiniloy"
    },
    {
        "id": 47,
        "title_bn": "অভিনয়ের মানুষ",
        "title_en": "Abhinoyer Manush",
        "author_bn": "আতিক রহমান",
        "author_en": "Atiq Rahman",
        "category": "Drama",
        "tags": ["drama", "theatre"],
        "price": 310,
        "discount_price": 270,
        "language": "Bangla",
        "cover_image": "https://www.boipokabd.com/storage/app/public/product/thumbnail/2024-01-04-659655865d3e0.png",
        "description": "মঞ্চ ও জীবনের ভিন্ন ভিন্ন অভিনয়ের গল্প।",
        "publication": "Panjeri"
    },
    {
        "id": 48,
        "title_bn": "স্বপ্ন ছোঁয়া দিন",
        "title_en": "Shopno Chhoa Din",
        "author_bn": "রেহান রহমান",
        "author_en": "Rehan Rahman",
        "category": "Fiction",
        "tags": ["fiction", "romance"],
        "price": 270,
        "discount_price": 230,
        "language": "Bangla",
        "cover_image": "https://www.boipokabd.com/storage/app/public/product/thumbnail/2024-01-04-659655865d3e0.png",
        "description": "ভালোবাসা আর স্বপ্নের একসাথে পথচলার কাহিনী।",
        "publication": "Tamralipi"
    },
    {
        "id": 49,
        "title_bn": "ছোট গল্পের ডায়েরি",
        "title_en": "Choto Golper Diary",
        "author_bn": "সাইফুল ইসলাম",
        "author_en": "Saiful Islam",
        "category": "Short Story",
        "tags": ["short story", "slice of life"],
        "price": 250,
        "discount_price": 210,
        "language": "Bangla",
        "cover_image": "https://www.boipokabd.com/storage/app/public/product/thumbnail/2024-01-04-659655865d3e0.png",
        "description": "নিত্য দিনের জীবনকে ঘিরে লেখা সংক্ষিপ্ত কিছু গল্প।",
        "publication": "Oitijjhya"
    },
    {
        "id": 50,
        "title_bn": "মেঘলা বিকেল",
        "title_en": "Meghla Bikel",
        "author_bn": "নওশীন তাবাসসুম",
        "author_en": "Naushin Tabassum",
        "category": "Drama",
        "tags": ["drama", "emotion"],
        "price": 260,
        "discount_price": 220,
        "language": "Bangla",
        "cover_image": "https://www.boipokabd.com/storage/app/public/product/thumbnail/2024-01-04-659655865d3e0.png",
        "description": "এক বিকেলের আবেগঘন নাট্যকাহিনী।",
        "publication": "Somoy Prokashon"
    }
]
